version: 2
jobs:
  deps:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}
      - run: go get -v
      - save_cache:
          key: v1-dependencies-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - persist_to_workspace:
          root: .
          paths:
            - ./

  test-unit:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}
      - run: make test

  test-acceptance:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}
      - run: echo "$GOOGLE_SERVICE_ACCOUNT_CREDS" | base64 --decode >/tmp/svc-account.json
      - run:
          command: make test
          environment:
            VAULT_ACC: "1"
            TEST_GOOGLE_CREDENTIALS_FILE: /tmp/svc-account.json

  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}
      - run: make build
      - persist_to_workspace:
          root: .
          paths:
            - ./

  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}
      - run: |
          curl -s https://api.github.com/repos/pantheon-systems/autotag/releases/latest | \
            grep browser_download | \
            grep -i linux | \
            cut -d '"' -f 4 | \
            xargs curl -o ~/autotag -L \
            && chmod 755 ~/autotag
      - run: ~/autotag
      - run: curl -sL https://git.io/goreleaser | bash -s -- --parallelism=2
      # goreleaser install script runs goreleaser automatically

workflows:
  version: 2
  primary:
    jobs:
      - deps
      - test-unit:
          requires:
            - deps
      - test-acceptance:
          requires:
            - deps
      - build:
          requires:
            - deps
      - release:
          requires:
            - test-unit
            - test-acceptance
            - build
          filters:
            branches:
              only:
                - master
                - gcp-cloud-hsm-mvp